# common

--- # local properties
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3309/payment?useSSL=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        ddl-auto: create-drop
    generate-ddl: true
    open-in-view: false
profile:
  message: "hi, local!"

--- # dev properties
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://${DB_URL:localhost}:3309/payment?useSSL=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        ddl-auto: create-drop
    generate-ddl: true
    open-in-view: false

profile:
  message: "hi, dev!"